Feature | Refactor business hour component adding rules
aloware/vue-business-hours pull request #3
Opened 2024-09-19 16:06 UTC by juanblariza-aloware

2024-09-19 19:10 UTC, nestor-aloware commented on src/components/BusinessHours.vue
> +      let newHours = Math.floor(totalMinutes / 60);
Could you use `minutesPerHour` instead of 60 here?

2024-09-19 19:48 UTC, nestor-aloware commented on src/components/BusinessHours.vue
> +      let newMinutes = totalMinutes % 60;
Could you use minutesPerHour instead of 60 here?

2024-09-19 19:49 UTC, nestor-aloware commented on src/components/BusinessHours.vue
> +      let newHours = Math.floor(totalMinutes / 60);
Could you use `minutesPerHour` instead of 60 here?

2024-09-19 19:49 UTC, nestor-aloware commented on src/components/BusinessHours.vue
> +      let newMinutes = totalMinutes % 60;
Could you use `minutesPerHour` instead of 60 here?

2024-09-19 19:51 UTC, nestor-aloware commented on src/components/BusinessHours.vue
> +      const minutesPerHour = 60;
if  `minutesPerHour ` `additionalHours ` are used in both functions. Wouln't be better to have them declared in data section?

2024-09-19 19:52 UTC, nestor-aloware commented on src/components/BusinessHoursSelect.vue
> +    <option v-show="isFirstRow(index) && onlyOneRow(hours)"
please re-order these properties according to this [guideline](https://aloware.atlassian.net/wiki/spaces/AM/pages/863961145/Guidelines#Talk2-%2F-Vue-(%5BinlineCard%5D-))

2024-09-19 19:55 UTC, nestor-aloware commented on src/components/BusinessHoursSelect.vue
> +<style scoped>
Generally we don't place the styles inside the components. We usually place them in `src\css\app.scss` or a proper .scss file

2024-09-19 19:55 UTC, nestor-aloware reviewed
Please check the comments.

2024-09-20 13:49 UTC, nestor-aloware approved these changes

2024-09-25 16:09 UTC, jefferson-aloware requested changes

2024-09-25 16:09 UTC, jefferson-aloware commented on src/components/BusinessHoursSelect.vue
> +  }
Move `props` to before `data`.

2024-09-25 19:47 UTC, jefferson-aloware approved these changes

2024-09-26 21:36 UTC, tito-aloware approved these changes

2024-09-26 21:37 UTC, tito-aloware commented
Holding this merge until the release

2025-12-04 00:54 UTC, closed without merging